-- require('Comment').setup({
--   toggler = {
--     ---Line-comment toggle keymap
--     line = 'gal',
--     ---Block-comment toggle keymap
--     block = 'gab',
--   },
--   opleader = {
--       ---Line-comment keymap
--       line = 'gal',
--       ---Block-comment keymap
--       block = 'gab',
--   },
-- })
