require("hop").setup()
vim.api.nvim_set_keymap("n", "<Leader>f", "<cmd>lua require'hop'.hint_words()<cr>", {})
-- vim.api.nvim_set_keymap("n", "<Leader>f", "<cmd>HopAnywhere<cr>", {})
vim.api.nvim_set_keymap("v", "<Leader>f", "<cmd>lua require('hop')[vim.fn.mode() == 'V' and 'hint_lines' or 'hint_words']({extend_visual = true})<cr>", {})
vim.api.nvim_set_keymap("n", "<c-w>f", ":HopLine<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("v", "<c-w>f", "<cmd>lua require'hop'.hint_lines({extend_visual = true})<cr>", { noremap = true, silent = true })
