# Kanagawa Alacritty Colors
colors:
  primary:
    background: '0x1f1f28'
    foreground: '0xdcd7ba'

  normal:
    black:   '0x090618'
    red:     '0xe46876'
    green:   '0x76946a'
    yellow:  '0xc0a36e'
    blue:    '0x7e9cd8'
    magenta: '0x957fb8'
    cyan:    '0x6a9589'
    white:   '0xc8c093'

  bright:
    black:   '0x727169'
    red:     '0xe46876'
    green:   '0x98bb6c'
    yellow:  '0xe6c384'
    blue:    '0x7fb4ca'
    magenta: '0x938aa9'
    cyan:    '0x7aa89f'
    white:   '0xdcd7ba'

  selection:
    background: '0x2d4f67'
    foreground: '0xc8c093'

  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }

font:
  # The size to use.
  size: 8
  # The normal (roman) font face to use.
  normal:
    family: Hack
    # Style can be specified to pick a specific face.

  # The bold font face
  bold:
    family: Hack
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Hack
    # Style can be specified to pick a specific face.
    style: Italic

key_bindings:
  - { key: Q, mods: Control, chars: "\x11" }
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: NumpadSubtract, mods: Control, action: None }

window:
  opacity: 0.8
