alias :q="exit"
alias cp="cp -i"
alias d="docker"
alias dc="docker compose"
alias ghw="gh repo view --web"
alias g="git"
alias cdkb="cd \$KBWO"
alias mkdir="mkdir -p"
alias sudo="sudo"
alias tod="cd ~/dotfiles"
alias y="yarn"
alias wayal="WINIT_UNIX_BACKEND=x11 alacritty"
alias vev=". .venv/bin/activate"
alias tmux='cd ~ && tmux'
