# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":now:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"
  # Emoji
  - trigger: ":ok:"
    replace: "👍"
  - trigger: ":next:"
    replace: "⏭️"
  - trigger: ":back:"
    replace: "⏮️"
  - trigger: ":check:"
    replace: "✅"
  - trigger: ":question:"
    replace: "❓"
  - trigger: ":exclamation:"
    replace: "❗"
  - trigger: ":warning:"
    replace: "⚠️"
  - trigger: ":info:"
    replace: "ℹ️"
  - trigger: ":stop:"
    replace: "🛑"
  - trigger: ":cross:"
    replace: "❌"

  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo 'Hello from your shell'"
