# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":now;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"
  - trigger: ":ts;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%s"
  - trigger: ":n;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"
  - trigger: ":d;"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ":w;"
    replace: "{{week}}"
    vars:
      - name: week
        type: date
        params:
          format: "%V"
  - trigger: ":yw;"
    replace: "{{yearweek}}"
    vars:
      - name: yearweek
        type: date
        params:
          format: "%Y-W%V"
  # Emoji
  - trigger: ":ok;"
    replace: "👍"
  - trigger: ":next;"
    replace: "⏭️"
  - trigger: ":nx;"
    replace: "⏭️"
  - trigger: ":back;"
    replace: "⏮️"
  - trigger: ":check;"
    replace: "✅"
  - trigger: ":ck;"
    replace: "✅"
  - trigger: ":question;"
    replace: "❓"
  - trigger: ":q;"
    replace: "❓"
  - trigger: ":exclamation;"
    replace: "❗"
  - trigger: ":warning;"
    replace: "⚠️"
  - trigger: ":info;"
    replace: "ℹ️"
  - trigger: ":stop;"
    replace: "🛑"
  - trigger: ":cross;"
    replace: "❌"
  - trigger: ":x;"
    replace: "❌"
  - trigger: ":speech;"
    replace: "💬"
  - trigger: ":construction;"
    replace: "🚧"
  - trigger: ":wip;"
    replace: "🚧"
  - trigger: ":rocket;"
    replace: "🚀"
  - trigger: ":eyes;"
    replace: "👀"

  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo 'Hello from your shell'"
