# Credit: https://github.com/mooz/xkeysnail/blob/bf3c93b4fe6efd42893db4e6588e5ef1c4909cfb/example/config.py#L62-L125
keymap:
  - name: All
    remap:
      C-h: backspace
modmap:
  - name: All
    remap:
      CapsLock: Control_L
